import zero from "./man_with_phone.png";
import one from "./woman_with_phone.png";
import two from "./seebeck_logo.svg";
import three from "./front_detail.png";
import four from "./box_detail.png";
import five from "./sholder_detail.png";
import six from "./man_with_phone_white.png";
import seven from "./woman_with_phone_black.png";
import eight from "./charging_together.png";
import nine from "./pep_logo.svg";

export const black = zero;
export const white = one;
export const logo = two;
export const front_detail = three;
export const box_detail = four;
export const sholder_detail = five;
export const man_with_phone_white = six;
export const woman_with_phone_black = seven;
export const charging_together = eight;
export const pep_logo = nine;
